### PR TITLE
Add libftdi1

### PR DESCRIPTION
**Pull request by nurikk**
Add libftdi1

Dependency for https://github.com/hyperion-project/hyperion.ng/pull/1595

### CODE REVIEW

**Comment by Paulchen-Panther** [comment]
Thank you @nurikk for the PR 👍 . I would have a small improvement for the DOCKER_CI check.

**Comment by nurikk** [comment]
> env.DOCKER_CI

I’m not sure that it will work, env.DOCKER_CI is undefined variable. And secret context isn’t available inside ‘if’ expression

**Comment by Paulchen-Panther** [comment]
> > env.DOCKER_CI
> 
> I’m not sure that it will work, env.DOCKER_CI is undefined variable. And secret context isn’t available inside ‘if’ expression

Small typo, sorry. Here is the correct example:
```
...
      - name: Publish to GitHub Container Registry
        env:
          enabledockerpublish: ${{ secrets.DOCKER_CI }}
        if: ${{ env.enabledockerpublish != null }}
        run: |
...
```

**Comment by nurikk-sa** [comment]
yep, that makes more sense

**Pull request merged**
